import DashboardHeader from "@/components/DashboardHeader";
import InstitutionSidebar from "@/components/institutionSidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function InstitutionLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex">
      <InstitutionSidebar />
      <main className="w-full flex flex-col">
        <DashboardHeader />
        <div className="h-[calc(100vh-70px)] overflow-scroll px-7 py-3">
          {children}
        </div>
      </main>
    </div>
  );
}
