import type { Metadata } from "next";
import { SidebarProvider } from "@/components/ui/sidebar";
import InstitutionSidebar from "@/components/InstitutionSidebar.tsx";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function InstitutionLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <SidebarProvider>
        <InstitutionSidebar />
        <main className="w-full px-7 py-3">{children}</main>
      </SidebarProvider>
    </>
  );
}
